### ISSUE TITLE
Make a bower lib

### ISSUE THREAD

**Issue by ThomasCrevoisier** [waterson/purescript-webaudio#1]
Hi,

Would it be possible for you to publish your project as a bower lib ? I'd love to use it for some personnal projects :)

**Comment by StijnRuts** [comment]
Seconded.

It is possible to install without having a bower lib by running
`bower install https://github.com/waterson/purescript-webaudio.git#master`
instead of
`bower install purescript-webaudio.git`

However, there is still issue #5.
