### ISSUE TITLE
Transferring to adkelley/purescript-webaudio

### ISSUE THREAD

**Issue by adkelley** [waterson/purescript-webaudio#8]
Hi Chris.  As you suspected, it's simpler and more straightforward to update, maintain, and submit this repository to `purescript-contrib` directly from my fork. Especially now that I've added Travis integration.  Within the next couple week, I would like to submit my fork to purescript-contrib, so that users can begin installing it directly via Bower.  If you agree with this approach, then please respond to this issue with your confirmation.  Thanks!

**Comment by waterson** [comment]
That works for me... let me know what you need me to do.

**Comment by adkelley** [comment]
Nothing required.  Thank you!
